### ISSUE TITLE
issue in cloning the solution

### ISSUE THREAD

**Issue by KyyB** [PMaynard/ICS-TestBed-Framework#2]
Hey PMaynard,

I tried cloning your solution on Ubuntu & received the following error:

"git@github.com: Permission denied (publickey). 

Please make sure you have the correct access rightsand the repository exists."

may you help me with that?

**Comment by Huey0513** [comment]
Sorry mate, that one was closed by my co-worker. I think that’s the reason why you cannot clone that.

Huey

From: KyyB
Sent: Monday, 6 January 2020 20:57
To: PMaynard/ICS-TestBed-Framework
Cc: Subscribed
Subject: [PMaynard/ICS-TestBed-Framework] issue in cloning the solution (#2)

Hey PMaynard,
I tried cloning your solution on Ubuntu & received the following error:
"git@github.com: Permission denied (publickey).
Please make sure you have the correct access rightsand the repository exists."
may you help me with that?

**Comment by cryp-xin** [comment]
Is there a workaround?  

> Hey PMaynard,
> 
> I tried cloning your solution on Ubuntu & received the following error:
> 
> "[git@github.com](mailto:git@github.com): Permission denied (publickey).
> 
> Please make sure you have the correct access rightsand the repository exists."
> 
> may you help me with that?

**Comment by PMaynard** [comment]
You need to use HTTPS to clone this repo.
e.g.
> git clone https://github.com/PMaynard/ICS-TestBed-Framework.git
